########################################## SINGLEVC  ##########################



resume: True
resume_path:
local_rank: 0

########################################## MEL-FEATURE ##########################
num_mels: 80
num_freq: 1025
n_fft: 1024
hop_size: 256
win_size: 1024
sampling_rate: 22050
fmin: 0
fmax: 8000
num_workers: 1


